CONFIG_DEBUG=y
CONFIG_GPIO=y
CONFIG_PWM=y

CONFIG_CONSOLE=y
CONFIG_SERIAL=y
CONFIG_UART_CONSOLE=y
CONFIG_UART_STM32=y

CONFIG_LOG=y
CONFIG_LOG_BACKEND_UART=y
CONFIG_LOG_DEFAULT_LEVEL=3

CONFIG_SENSOR=y
CONFIG_SENSOR_MS5611=y

CONFIG_SPI=y
CONFIG_SPI_LOG_LEVEL_DBG=y
CONFIG_SENSOR_LOG_LEVEL_DBG=y

CONFIG_CBPRINTF_FP_SUPPORT=y

CONFIG_FPU=y

# ADC subsystem
CONFIG_ADC=y

CONFIG_BMP581=n #disabilitato fino a quando non abbiamo supporto SPI

CONFIG_SENSOR_ASYNC_API=y

CONFIG_ICM4268X_DECODER=y
CONFIG_ICM4268X_TRIGGER_GLOBAL_THREAD=y # probabilmente questo va abilitato
CONFIG_ICM4268X_TRIGGER_OWN_THREAD=n

# Abilita l'API Flash
CONFIG_FLASH=y

# Abilita il driver specifico per SPI NOR (gestisce comandi JEDEC)
CONFIG_SPI_NOR=y

# Opzionale: Ottimizzazioni per flash grandi (>16MB)
CONFIG_SPI_NOR_FLASH_LAYOUT_PAGE_SIZE=4096

# Configuazione del driver SDMMC (da controllare)
CONFIG_DISK_ACCESS=y
CONFIG_FILE_SYSTEM=y
CONFIG_DISK_DRIVER_SDMMC=y
CONFIG_SDMMC_STM32=y


# i2c
CONFIG_I2C=y
CONFIG_MCP9600=y
CONFIG_INA219=y

#CONFIG_PRINTK=y
CONFIG_DMA=y
CONFIG_DCACHE=n



CONFIG_LED_STRIP=y
CONFIG_LED_STRIP_LOG_LEVEL_DBG=y
CONFIG_UART_ASYNC_API=y
CONFIG_UART_USE_RUNTIME_CONFIGURE=y

# --- SOTTOSISTEMA LED ---
CONFIG_LED_STRIP=y

# --- ABILITAZIONE SERIALE E DMA BASE ---
CONFIG_SERIAL=y
CONFIG_DMA=y

# --- DRIVER SPECIFICI STM32 ---
CONFIG_UART_STM32=y
CONFIG_DMA_STM32=y

# --- API ASINCRONA (Richiesta dal WS2812) ---
CONFIG_UART_ASYNC_API=y

CONFIG_HEAP_MEM_POOL_SIZE=4096

# Attiva il supporto DMA e UART Asincrona
CONFIG_SERIAL=y
CONFIG_UART_ASYNC_API=y
CONFIG_DMA=y

CONFIG_SERVO=y
CONFIG_SERVO_GENERIC_PWM=y
