manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.3.0
      path: zephyr
      import:
        name-allowlist:
          - cmsis_6
          - hal_stm32
          - loramac-node
          - lora-basics-modem
          - hal_semtech
          - fatfs
          - littlefs