CONFIG_DEBUG=y
CONFIG_GPIO=y
CONFIG_SPI=y
CONFIG_LED_STRIP=y
CONFIG_WS2812_STRIP_SPI=y

CONFIG_CONSOLE=y
CONFIG_SERIAL=y
CONFIG_UART_CONSOLE=y
CONFIG_NOCACHE_MEMORY=y

CONFIG_LOG=y
CONFIG_LOG_BACKEND_UART=y
CONFIG_LOG_DEFAULT_LEVEL=3

CONFIG_SENSOR=y

# Enable DMA for SPI to achieve the timing requirements of WS2812 LEDs
CONFIG_SPI_STM32_DMA=y
CONFIG_DMA=y
CONFIG_DCACHE=y
CONFIG_WS2812_STRIP_SPI_FORCE_NOCACHE=y