CONFIG_DEBUG=y

CONFIG_GPIO=y

CONFIG_CONSOLE=y
CONFIG_SERIAL=y
CONFIG_UART_CONSOLE=y
CONFIG_SPI=y

CONFIG_LOG=y
CONFIG_LOG_BACKEND_UART=y
CONFIG_LOG_DEFAULT_LEVEL=3

CONFIG_PRINTK=y

CONFIG_PWM=y
CONFIG_PWM_STM32=y

CONFIG_SPI_STM32_DMA=y
CONFIG_DMA=y
CONFIG_DMA_STM32=y
CONFIG_DCACHE=n

# LED strip support
CONFIG_LED_STRIP=y
CONFIG_WS2812_GPIO_STM32=y

CONFIG_LORA=y
CONFIG_LORA_LOG_LEVEL_DBG=y
CONFIG_LORA_INIT_PRIORITY=90
CONFIG_LORA_SX126X=y