CONFIG_DEBUG=y

CONFIG_GPIO=y
CONFIG_FPU=y

CONFIG_CONSOLE=y
CONFIG_SERIAL=y
CONFIG_UART_CONSOLE=y
CONFIG_UART_STM32=y
CONFIG_UART_INTERRUPT_DRIVEN=y #TODO: change to DMA mode

CONFIG_PRINTK=y


CONFIG_LOG=y
CONFIG_LOG_BACKEND_UART=y
CONFIG_LOG_DEFAULT_LEVEL=3

CONFIG_SPI=y
CONFIG_I2C=y

CONFIG_LORA=y

CONFIG_LED=y
CONFIG_LED_GPIO=y
